### ISSUE TITLE
Site-Specific Rich Presence for Web Players (Browsers)

### ISSUE THREAD

**Issue by lazykern** [lazykern/mprisence#43]
**Please Describe The Problem To Be Solved**
Currently, when listening to a web-based music service (like SoundCloud, YouTube Music, Bandcamp) within a browser (e.g., Firefox, Zen, Chrome), `mprisence` displays the presence generically for the browser itself (e.g., "Listening to Zen"). This isn't very informative as the user is primarily interacting with the web service, not just the browser application.

**In Scope:**
*   Detecting specific known web services playing within supported browsers.
*   Allowing global configuration to customize the Rich Presence (App ID, icon, potentially templates/activity type) based on the detected web service, regardless of which browser is used.

**Out of Scope:**
*   Detecting *every* possible media website automatically. Configuration for specific sites will likely be required.
*   Deep integration requiring browser extensions. This should rely on existing MPRIS metadata.

**(Optional): Suggest A Solution**
Implement **Site-Specific Presence** using a global configuration:

1.  **Metadata Inspection:** Enhance the metadata processing (likely in `src/metadata.rs` or `src/presence.rs`) to check `xesam:url` and potentially `xesam:title` from browser players for patterns matching known services (e.g., `soundcloud.com`, `music.youtube.com`).
2.  **Global Configuration Schema:** Add a new top-level table to `config.toml`, such as `[websites]`. Inside this section, users define configurations for specific sites:
    ```toml
    enable_site_detection = true 

    [websites.soundcloud]
    match_pattern = "soundcloud.com" 
    app_id = "YOUR_SOUNDCLOUD_APP_ID" 
    icon = "URL_TO_SOUNDCLOUD_ICON"


    [websites.youtubemusic]
    match_pattern = "music.youtube.com"
    app_id = "YOUR_YOUTUBE_MUSIC_APP_ID"
    icon = "URL_TO_YOUTUBE_MUSIC_ICON"
    ```

**Tradeoffs:**
*   Relies on browsers providing useful `xesam:url` or `xesam:title` via MPRIS. Some browsers/sites might not provide enough information.
*   Requires users to configure the sites they care about and potentially find/create Discord App IDs and icon URLs for them.

**Future Considerations:**
*   Could potentially ship with *default* configurations (icons, maybe even generic App IDs if feasible) for very common services in `config.default.toml` that users can override in their `config.toml`.
